// gencompletions writes the CLI's static shell completion scripts to files so
// the release workflow can package them into the deb and Homebrew formula. Run
// from the repo root:
//
//	go run ./tools/gencompletions      # writes completions/{hemma.bash,_hemma.zsh}
//
// Single source of truth: the same cli.BashCompletion / cli.ZshCompletion
// strings back `hemma completion <shell>`, so the files can never drift from
// what the binary prints. Mirrors tools/genman; completions/ is gitignored and
// regenerated by the release workflow.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"hemma/internal/cli"
)

func main() {
	dir := flag.String("dir", "completions", "output directory")
	flag.Parse()

	if err := os.MkdirAll(*dir, 0o755); err != nil {
		fatal(err)
	}
	write(filepath.Join(*dir, "hemma.bash"), cli.BashCompletion)
	write(filepath.Join(*dir, "_hemma.zsh"), cli.ZshCompletion)
}

func write(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fatal(err)
	}
	fmt.Println("wrote", path)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gencompletions:", err)
	os.Exit(1)
}
