# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hemma < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq), Caddy site blocks, and auth-provider config from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-hemma"
  version "0.36.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.36.0/hemma_0.36.0_darwin_amd64.tar.gz"
      sha256 "aa882dc341743c0a69501ebe1e1756906924a9aa6e8ee2ceb3c8734fdd4540c9"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.36.0/hemma_0.36.0_darwin_arm64.tar.gz"
      sha256 "2703b24d56250be6fe986db867f6665196ca372f4ed744db63dc7b70230253a8"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.36.0/hemma_0.36.0_linux_amd64.tar.gz"
      sha256 "6937e5dab9d80db133425190cad4ba467359f6eeb98b13d10a6a90f0935da8da"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.36.0/hemma_0.36.0_linux_arm64.tar.gz"
      sha256 "3ca43f5ac5f8bbf7447475d49b2af6789ab21d409818a891a23736faa8a7a7dd"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  test do
    assert_match "hemma", shell_output("#{bin}/hemma version")
  end
end
