# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hemma < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq), Caddy site blocks, and auth-provider config from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-hemma"
  version "0.29.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.1/hemma_0.29.1_darwin_amd64.tar.gz"
      sha256 "bffe2a96231d73a049c27a8807958a4808f0e4d7b297ec461d27919a2f78981f"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.1/hemma_0.29.1_darwin_arm64.tar.gz"
      sha256 "59da87a8da596dc248532e07e334775c7b12f09940b25d7ce37b5bd58bf637cd"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.1/hemma_0.29.1_linux_amd64.tar.gz"
      sha256 "7f8a92b8c704927537cc06b1afd05bb3406107ea43dbdc1144e3005d9c915805"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.29.1/hemma_0.29.1_linux_arm64.tar.gz"
      sha256 "8abdc9d3e434fdd97fcc1053ad894dd0a3222eb2876f0b8bc03513d7a23244f5"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  test do
    assert_match "hemma", shell_output("#{bin}/hemma version")
  end
end
