# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hemma < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq), Caddy site blocks, and auth-provider config from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-hemma"
  version "0.28.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.28.0/hemma_0.28.0_darwin_amd64.tar.gz"
      sha256 "2e3347103345200a2f2b3fd3b561359942a96a69f4767718d9b9a8783657bf3d"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.28.0/hemma_0.28.0_darwin_arm64.tar.gz"
      sha256 "1e3d2f64cc7cbe2924a6665acf0adc9c758c1f04f8f2b2196fb4678ece2c1fcd"

      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.28.0/hemma_0.28.0_linux_amd64.tar.gz"
      sha256 "1209a90ab427761c7c554280c5f65c04608a93ba6b9f03ec93cd3564c687af69"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-hemma/releases/download/v0.28.0/hemma_0.28.0_linux_arm64.tar.gz"
      sha256 "e13f6f7631b063dc88d637294f0a4f5b628adb5657b75c4496ed74cbe7513b4b"
      define_method(:install) do
        bin.install "hemma"
        # Backwards-compatible alias: `splitdns` keeps working for all commands.
        bin.install_symlink "hemma" => "splitdns"
        man1.install "man/hemma.1.gz"
        bash_completion.install "completions/hemma.bash" => "hemma"
        zsh_completion.install "completions/_hemma.zsh" => "_hemma"
      end
    end
  end

  test do
    assert_match "hemma", shell_output("#{bin}/hemma version")
  end
end
