# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitdns < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-splitdns"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.19.0/splitdns_0.19.0_darwin_amd64.tar.gz"
      sha256 "223f52e607a68e8d8ad95231a76819ff5aeb49d5d89afd9e8aed7ffb7d0302d8"

      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.19.0/splitdns_0.19.0_darwin_arm64.tar.gz"
      sha256 "ead31dec35084e8ddea9441610c7e5a5c83fc45cfb9cd2e1e4637362fd5ab5bd"

      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.19.0/splitdns_0.19.0_linux_amd64.tar.gz"
      sha256 "9e901391fc582ed56f48b55ee343d06c65e79590cd69d57653285a82915660f9"
      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.19.0/splitdns_0.19.0_linux_arm64.tar.gz"
      sha256 "c803651bb659da10a09dda9842ba277399084ee8db6d4f64d5d84ec75f740a92"
      define_method(:install) do
        bin.install "splitdns"
        man1.install "man/splitdns.1.gz"
      end
    end
  end

  test do
    assert_match "splitdns", shell_output("#{bin}/splitdns version")
  end
end
