# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitdns < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-splitdns"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.13.0/splitdns_0.13.0_darwin_amd64.tar.gz"
      sha256 "d340f4728841ba57b56f618c4a3e4d772fc090b49d4ba2b816458c1546553f84"

      define_method(:install) do
        bin.install "splitdns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.13.0/splitdns_0.13.0_darwin_arm64.tar.gz"
      sha256 "b54411e143350d907cd1e2eec4befa6d5431da814a30a8fb3fbc0f32b8683455"

      define_method(:install) do
        bin.install "splitdns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.13.0/splitdns_0.13.0_linux_amd64.tar.gz"
      sha256 "015dcae4e1db3074686c22c8e4ba90a7dc330878ef07e4c6c12f77ba697b652e"
      define_method(:install) do
        bin.install "splitdns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-splitdns/releases/download/v0.13.0/splitdns_0.13.0_linux_arm64.tar.gz"
      sha256 "5bad45211f8d463efdfe3bc7a5b3a4e50309ebf85ec751b3af5f7dd1a6fb4654"
      define_method(:install) do
        bin.install "splitdns"
      end
    end
  end

  test do
    assert_match "splitdns", shell_output("#{bin}/splitdns version")
  end
end
