# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splitdns < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-sd"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.11.0/splitdns_0.11.0_darwin_amd64.tar.gz"
      sha256 "915c70b0998bdbc7a95bbcdefd050b38df7218684848e4b6790b417f46d90454"

      define_method(:install) do
        bin.install "splitdns"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.11.0/splitdns_0.11.0_darwin_arm64.tar.gz"
      sha256 "297f00ffcc7b295e6610d6b3e5331175686a9dd4cd4c646d4ae8fc0a2534ffd8"

      define_method(:install) do
        bin.install "splitdns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.11.0/splitdns_0.11.0_linux_amd64.tar.gz"
      sha256 "d197491636015ed862f5dd0bdfba8278ba5eb977e7f9dbced19c390866a6ae12"
      define_method(:install) do
        bin.install "splitdns"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-sd/releases/download/v0.11.0/splitdns_0.11.0_linux_arm64.tar.gz"
      sha256 "ef247bfd13173b9a0f044fb6ef54a3be6bff5c571b2712d0c701e619227df989"
      define_method(:install) do
        bin.install "splitdns"
      end
    end
  end

  test do
    assert_match "splitdns", shell_output("#{bin}/splitdns version")
  end
end
