package auth

import (
	"os"
	"os/exec"
	"strings"
	"testing"
)

// TestSmoke_AutheliaValidatesDigests is the live compatibility check: digests
// generated by the native Go code must validate against the real Authelia
// binary (`authelia crypto hash validate`). It shells out to docker, so it is
// gated behind SPLITDNS_SMOKE=1 — run manually before releasing crypto
// changes:
//
//	SPLITDNS_SMOKE=1 go test ./internal/auth -run Smoke -v
func TestSmoke_AutheliaValidatesDigests(t *testing.T) {
	if os.Getenv("SPLITDNS_SMOKE") == "" {
		t.Skip("set SPLITDNS_SMOKE=1 to run the live authelia validation (needs docker)")
	}
	if _, err := exec.LookPath("docker"); err != nil {
		t.Fatal("docker is required for the smoke test")
	}

	validate := func(password, digest string) string {
		t.Helper()
		out, err := exec.Command("docker", "run", "--rm", "authelia/authelia:latest",
			"authelia", "crypto", "hash", "validate", "--password", password, "--", digest).CombinedOutput()
		if err != nil {
			t.Fatalf("authelia validate failed: %v\n%s", err, out)
		}
		return strings.TrimSpace(string(out))
	}

	_, secret, digest, err := (authelia{}).GenerateOIDCClient()
	if err != nil {
		t.Fatal(err)
	}
	if got := validate(secret, digest); !strings.Contains(got, "The password matches the digest.") {
		t.Errorf("pbkdf2: authelia said %q", got)
	} else {
		t.Logf("pbkdf2-sha512: %s", got)
	}

	const pw = "smoke-test-password"
	userDigest, err := (authelia{}).HashUserPassword(pw)
	if err != nil {
		t.Fatal(err)
	}
	if got := validate(pw, userDigest); !strings.Contains(got, "The password matches the digest.") {
		t.Errorf("argon2id: authelia said %q", got)
	} else {
		t.Logf("argon2id: %s", got)
	}
}
