// Package render produces the file contents for dnsmasq .conf and Caddy
// .caddy outputs (design §4).
package render

import (
	"fmt"
	"strings"

	"hemma/internal/config"
)

// Header marks generated files. Identical across both output types.
const Header = "# GENERATED by hemma — do not edit. Source: services.yaml"

// CaddyImportFile is the content of hemma.generated.caddy — the single file
// every host's Caddyfile should import. Order matters: the auth snippet
// and tls snippets must be defined before the site blocks that reference them.
const CaddyImportFile = Header + "\n" +
	"import " + AuthSnippetFilename + "\n" +
	"import tls/*.caddy\n" +
	"import sites/*.caddy\n"

// CaddyImportFilename is the name of the generated import file.
const CaddyImportFilename = "hemma.generated.caddy"

// AuthSnippetName is the Caddy snippet name every protected site imports. It is
// "auth" — the concept, never a provider name — so swapping the
// backing provider is a content change in one file, not a rename everywhere.
const AuthSnippetName = "auth"

// AuthSnippetFilename is the generated file holding the (auth) snippet. It sits
// directly in caddy/data/ (a sibling of hemma.generated.caddy), so it is not
// picked up by the sites/*.caddy or tls/*.caddy globs and must be imported by
// name — which CaddyImportFile does, before the site blocks.
const AuthSnippetFilename = "hemma.auth.generated.caddy"

// AuthSnippet renders the (auth) snippet file. When body is non-empty it is the
// user-provided auth directive(s) (copied verbatim from defaults.auth_snippet);
// when empty, an empty (auth) {} stub is emitted. Every site block imports
// (auth) unconditionally, so the empty stub is a deliberate no-op: it lets a
// service opt in via `import auth` while global auth is off, and lets auth be
// turned on/off by changing this one file's content rather than rewriting sites.
func AuthSnippet(body string) string {
	inner := strings.TrimRight(body, "\n")
	if inner == "" {
		return fmt.Sprintf("%s\n(%s) {\n}\n", Header, AuthSnippetName)
	}
	// Indent each line of the provided body one tab into the snippet block.
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n(%s) {\n", Header, AuthSnippetName)
	for _, line := range strings.Split(inner, "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("\t")
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// TLSSnippetName derives the Caddy snippet name for a domain: tls_ followed by
// the domain with dots replaced by underscores (e.g. example.com ->
// tls_example_com). Deterministic and collision-free across TLDs.
func TLSSnippetName(domain string) string {
	return "tls_" + strings.ReplaceAll(domain, ".", "_")
}

// TLSSnippet renders the Caddy (tls_<domain>) snippet that points at the
// domain's wildcard cert. The cert path convention is fixed:
// /etc/caddy/certs/<domain>/{fullchain.cer,privkey.key} (design §4.3). The
// tool generates this so a domain needs no hand-written Caddyfile snippet.
func TLSSnippet(domain string) string {
	return fmt.Sprintf(
		"%s\n(%s) {\n\ttls /etc/caddy/certs/%s/fullchain.cer /etc/caddy/certs/%s/privkey.key\n}\n",
		Header, TLSSnippetName(domain), domain, domain)
}

// DNSRecord renders the dnsmasq directives for a service.
//
//   - local=/<fqdn>/ makes dnsmasq authoritative for the WHOLE name, so query
//     types with no local record — notably the HTTPS/SVCB (type 65) record —
//     return NODATA instead of being forwarded upstream and cached. Required:
//     address= alone only covers A/AAAA; without local=, dnsmasq forwards the
//     HTTPS query to Cloudflare, and SVCB-aware clients (Safari, Chrome/Edge)
//     follow its public endpoint hint, bypassing split-horizon. (Verified: with
//     local= type 65 is NODATA; without it, type 65 is the cached Cloudflare
//     record.)
//   - the A record points at hostIP (the host that RUNS the service).
//   - address=/<fqdn>/:: suppresses the public AAAA; :: (unspecified) is
//     correct, ::1 (loopback) is a bug (design §4.1).
func DNSRecord(fqdn, hostIP string) string {
	return fmt.Sprintf("%s\nlocal=/%s/\naddress=/%s/%s\naddress=/%s/::\n",
		Header, fqdn, fqdn, hostIP, fqdn)
}

// CaddySite renders the Caddy site block for a service. tlsImport is the
// snippet name (e.g. tls_example_com); backend is emitted verbatim as the
// reverse_proxy upstream (design §4.2).
//
// The auth mode decides what gate (if any) is emitted before reverse_proxy:
//   - AuthForward imports the (auth) snippet before proxying — every request
//     goes through the forward-auth check. auth.bypass_paths are deliberately NOT
//     rendered here: the auth provider's generated bypass rules (design §4.5,
//     auth.AccessControl) are the single policy engine, so Caddy emits no
//     per-path branches that could drift from them.
//   - AuthOIDC, AuthExternal and AuthNone all render a PLAIN reverse_proxy (no
//     import auth) — byte-identical output for the three. Forward is the only
//     mode gated here because it is the only one where hemma IS the gate: an
//     oidc app runs the flow itself, an external one is gated by something hemma
//     cannot see (the app's own login, an API token, an edge proxy such as
//     Cloudflare Access), and none has no gate at all.
//     Identical output is precisely why the mode is still recorded: it survives
//     in services.yaml and in `list`, so a protected service is never
//     indistinguishable from an unprotected one just because their Caddy blocks
//     match. (config.AuthMode.UsesProvider draws the other line — which modes
//     Authelia validates — and puts oidc with forward, not with external.)
//
// authBackend is orthogonal to the mode: when true (this service is the
// forward-auth portal) the reverse_proxy preserves the inbound X-Forwarded-Host
// so post-login redirects target the original service, not the portal.
func CaddySite(fqdn, tlsImport, backend string, mode config.AuthMode, authBackend bool) string {
	// The forward-auth backend (e.g. an Authelia portal) must preserve the inbound
	// X-Forwarded-Host through the reverse_proxy. When a protected service's
	// auth check hits this backend, Caddy's outer hop already set
	// X-Forwarded-Host to the *original* service host; a plain reverse_proxy
	// would reset it to this block's host (the auth domain), making Authelia
	// treat itself as the target and loop the post-login redirect. Preserving it
	// is safe: the value is whatever the trusted outer Caddy hop computed, not
	// anything a client can spoof.
	proxyLine := fmt.Sprintf("reverse_proxy %s", backend)
	if authBackend {
		proxyLine = fmt.Sprintf("reverse_proxy %s {\n\t\theader_up X-Forwarded-Host {header.X-Forwarded-Host}\n\t}", backend)
	}

	// AuthForward: one uniform shape — import auth, then proxy. No handle
	// wrappers: with a single branch they add nothing, and per-path public
	// branches are the auth provider's job now.
	if mode == config.AuthForward {
		return fmt.Sprintf("%s\n%s {\n\timport %s\n\timport %s\n\t%s\n}\n",
			Header, fqdn, tlsImport, AuthSnippetName, proxyLine)
	}
	return fmt.Sprintf("%s\n%s {\n\timport %s\n\t%s\n}\n", Header, fqdn, tlsImport, proxyLine)
}

// ComposeOverrideFilename is the compose auto-merge name hemma writes into
// each host's repo dir, alongside (never editing) the hand-maintained
// docker-compose.yml. Compose loads it with zero flags because "docker-
// compose.override.yml" is one of its two recognized override names —
// verified empirically: compose.override.yaml/.yml and docker-compose.
// override.yaml/.yml all auto-merge; any other basename (docker-compose.
// hemma.yml, myapp.override.yaml, ...) silently does not.
const ComposeOverrideFilename = "docker-compose.override.yml"

// ComposeOverrideEntry is one service's public-horizon labels.
type ComposeOverrideEntry struct {
	// Name is the service/container name — the compose services key.
	Name string
	// Hostname is the tunnel ingress hostname (cloudflare.io/hostname).
	Hostname string
	// ReverseProxy is true unless this service IS the auth_service: routing
	// the auth backend itself through Caddy would recurse through its own
	// (auth) gate (design §12 auth-bypass exemption; plan.go applies the same
	// name == c.Defaults.AuthService check that guards CaddySite's authBackend
	// param).
	ReverseProxy bool
}

// ComposeOverride renders docker-compose.override.yml for one host: a
// services.<name>.labels block per public entry, replacing the hand-written
// cloudflare.io/* labels this repo used to carry directly in docker-
// compose.yml. Docker Compose merges labels key-by-key against the base
// file (locally defined — i.e. override-file — values win), so this is safe
// to auto-merge over whatever (if anything) remains in docker-compose.yml.
// Entries are rendered in the order given; callers sort by name for a stable
// diff.
func ComposeOverride(entries []ComposeOverrideEntry) string {
	var b strings.Builder
	b.WriteString(Header)
	b.WriteString("\nservices:\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  %s:\n    labels:\n      cloudflare.io/hostname: %q\n", e.Name, e.Hostname)
		if e.ReverseProxy {
			b.WriteString("      cloudflare.io/reverseproxy: \"https://caddy:443\"\n")
		}
	}
	return b.String()
}
