// Package render produces the file contents for dnsmasq .conf and Caddy
// .caddy outputs (design §4).
package render

import (
	"fmt"
	"strings"

	"hemma/internal/config"
)

// Header marks generated files. Identical across both output types.
const Header = "# GENERATED by hemma — do not edit. Source: services.yaml"

// CaddyImportFile is the content of hemma.generated.caddy — the single file
// every host's Caddyfile should import. Order matters: the auth snippet
// and tls snippets must be defined before the site blocks that reference them.
const CaddyImportFile = Header + "\n" +
	"import " + AuthSnippetFilename + "\n" +
	"import tls/*.caddy\n" +
	"import sites/*.caddy\n"

// CaddyImportFilename is the name of the generated import file.
const CaddyImportFilename = "hemma.generated.caddy"

// AuthSnippetName is the Caddy snippet name every protected site imports. It is
// "auth" — the concept, never a provider name — so swapping the
// backing provider is a content change in one file, not a rename everywhere.
const AuthSnippetName = "auth"

// AuthSnippetFilename is the generated file holding the (auth) snippet. It sits
// directly in caddy/data/ (a sibling of hemma.generated.caddy), so it is not
// picked up by the sites/*.caddy or tls/*.caddy globs and must be imported by
// name — which CaddyImportFile does, before the site blocks.
const AuthSnippetFilename = "hemma.auth.generated.caddy"

// AuthSnippet renders the (auth) snippet file. When body is non-empty it is the
// user-provided auth directive(s) (copied verbatim from defaults.auth_snippet);
// when empty, an empty (auth) {} stub is emitted. Every site block imports
// (auth) unconditionally, so the empty stub is a deliberate no-op: it lets a
// service opt in via `import auth` while global auth is off, and lets auth be
// turned on/off by changing this one file's content rather than rewriting sites.
func AuthSnippet(body string) string {
	inner := strings.TrimRight(body, "\n")
	if inner == "" {
		return fmt.Sprintf("%s\n(%s) {\n}\n", Header, AuthSnippetName)
	}
	// Indent each line of the provided body one tab into the snippet block.
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n(%s) {\n", Header, AuthSnippetName)
	for _, line := range strings.Split(inner, "\n") {
		if line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("\t")
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// TLSSnippetName derives the Caddy snippet name for a domain: tls_ followed by
// the domain with dots replaced by underscores (e.g. example.com ->
// tls_example_com). Deterministic and collision-free across TLDs.
func TLSSnippetName(domain string) string {
	return "tls_" + strings.ReplaceAll(domain, ".", "_")
}

// TLSSnippet renders the Caddy (tls_<domain>) snippet that points at the
// domain's wildcard cert. The cert path convention is fixed:
// /etc/caddy/certs/<domain>/{fullchain.cer,privkey.key} (design §4.3). The
// tool generates this so a domain needs no hand-written Caddyfile snippet.
func TLSSnippet(domain string) string {
	return fmt.Sprintf(
		"%s\n(%s) {\n\ttls /etc/caddy/certs/%s/fullchain.cer /etc/caddy/certs/%s/privkey.key\n}\n",
		Header, TLSSnippetName(domain), domain, domain)
}

// DNSRecord renders the dnsmasq directives for a service.
//
//   - local=/<fqdn>/ makes dnsmasq authoritative for the WHOLE name, so query
//     types with no local record — notably the HTTPS/SVCB (type 65) record —
//     return NODATA instead of being forwarded upstream and cached. Required:
//     address= alone only covers A/AAAA; without local=, dnsmasq forwards the
//     HTTPS query to Cloudflare, and SVCB-aware clients (Safari, Chrome/Edge)
//     follow its public endpoint hint, bypassing split-horizon. (Verified: with
//     local= type 65 is NODATA; without it, type 65 is the cached Cloudflare
//     record.)
//   - the A record points at hostIP (the host that RUNS the service).
//   - address=/<fqdn>/:: suppresses the public AAAA; :: (unspecified) is
//     correct, ::1 (loopback) is a bug (design §4.1).
func DNSRecord(fqdn, hostIP string) string {
	return fmt.Sprintf("%s\nlocal=/%s/\naddress=/%s/%s\naddress=/%s/::\n",
		Header, fqdn, fqdn, hostIP, fqdn)
}

// CaddySite renders the Caddy site block for a service. tlsImport is the
// snippet name (e.g. tls_example_com); backend is emitted verbatim as the
// reverse_proxy upstream (design §4.2).
//
// The auth mode decides what gate (if any) is emitted before reverse_proxy:
//   - AuthForward imports the (auth) snippet before proxying — every request
//     goes through the forward-auth check. auth.bypass_paths are deliberately NOT
//     rendered here: the auth provider's generated bypass rules (design §4.5,
//     auth.AccessControl) are the single policy engine, so Caddy emits no
//     per-path branches that could drift from them.
//   - AuthOIDC, AuthExternal and AuthNone all render a PLAIN reverse_proxy (no
//     import auth) — byte-identical output for the three. Forward is the only
//     mode gated here because it is the only one where hemma IS the gate: an
//     oidc app runs the flow itself, an external one is gated by something hemma
//     cannot see (the app's own login, an API token, an edge proxy such as
//     Cloudflare Access), and none has no gate at all.
//     Identical output is precisely why the mode is still recorded: it survives
//     in services.yaml and in `list`, so a protected service is never
//     indistinguishable from an unprotected one just because their Caddy blocks
//     match. (config.AuthMode.UsesProvider draws the other line — which modes
//     Authelia validates — and puts oidc with forward, not with external.)
//
// authBackend is orthogonal to the mode: when true (this service is the
// forward-auth portal) the reverse_proxy preserves the inbound X-Forwarded-Host
// so post-login redirects target the original service, not the portal.
func CaddySite(fqdn, tlsImport, backend string, mode config.AuthMode, authBackend bool) string {
	// The forward-auth backend (e.g. an Authelia portal) must preserve the inbound
	// X-Forwarded-Host through the reverse_proxy. When a protected service's
	// auth check hits this backend, Caddy's outer hop already set
	// X-Forwarded-Host to the *original* service host; a plain reverse_proxy
	// would reset it to this block's host (the auth domain), making Authelia
	// treat itself as the target and loop the post-login redirect. Preserving it
	// is safe: the value is whatever the trusted outer Caddy hop computed, not
	// anything a client can spoof.
	proxyLine := fmt.Sprintf("reverse_proxy %s", backend)
	if authBackend {
		proxyLine = fmt.Sprintf("reverse_proxy %s {\n\t\theader_up X-Forwarded-Host {header.X-Forwarded-Host}\n\t}", backend)
	}

	// AuthForward: one uniform shape — import auth, then proxy. No handle
	// wrappers: with a single branch they add nothing, and per-path public
	// branches are the auth provider's job now.
	if mode == config.AuthForward {
		return fmt.Sprintf("%s\n%s {\n\timport %s\n\timport %s\n\t%s\n}\n",
			Header, fqdn, tlsImport, AuthSnippetName, proxyLine)
	}
	return fmt.Sprintf("%s\n%s {\n\timport %s\n\t%s\n}\n", Header, fqdn, tlsImport, proxyLine)
}

// CloudflaredConfigFilename is the file hemma writes wholesale into each
// host's configured tunnel directory (defaults.tunnel_dir — one repo-wide
// path, required before any public: true service can plan), replacing what
// used to be a hand-maintained near-empty stub plus per-service
// cloudflare.io/* compose labels. cloudflared-wrapper mounts this directory
// as /etc/cloudflared and reads config.yml as its base config on every start.
const CloudflaredConfigFilename = "config.yml"

// CloudflaredIngressEntry is one public service's tunnel ingress rule.
type CloudflaredIngressEntry struct {
	// Hostname is the public FQDN cloudflared routes.
	Hostname string
	// Backend is the ingress "service" value. Always routed through Caddy
	// (https://caddy:443) — no per-service bypass: the redirect-loop concern
	// that once justified an auth_service exemption lives in the auth MODE,
	// not in "does traffic pass through Caddy", and planService already
	// refuses to let the auth_service carry any auth mode at all, so its
	// Caddy site never imports (auth) regardless of how public traffic
	// reaches it. cloudflared-wrapper's writeMergedConfig injects the
	// originServerName/httpHostHeader SNI+Host fix for every https:// ingress
	// entry regardless of where it came from (a label OR a raw config.yml
	// entry, as of cloudflared-wrapper commit c0c68cd) — hemma does not need
	// to (and deliberately does not) write that block itself.
	Backend string
}

// CloudflaredConfig renders config.yml for one host: one ingress rule per
// public entry, terminated by the mandatory catch-all. hemma writes this file
// WHOLESALE — no merge with anything hand-written, since there is no longer
// any hand-editing of a host's cloudflared config (design §12: hemma is the
// sole author, same posture as a Caddy site file). The catch-all is written
// explicitly rather than relied upon from cloudflared-wrapper's own missing-
// catch-all fallback, since ingress match order matters (it must be last) and
// a generator should not depend on a consumer's forgiveness for something it
// can trivially guarantee itself. Entries are rendered in the order given;
// callers sort by hostname for a stable diff.
func CloudflaredConfig(entries []CloudflaredIngressEntry) string {
	var b strings.Builder
	b.WriteString(Header)
	b.WriteString("\ningress:\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "  - hostname: %s\n    service: %s\n", e.Hostname, e.Backend)
	}
	b.WriteString("  - service: http_status:404\n")
	return b.String()
}
